domain: slingtsi.hershamin.me
url: https://slingtsi.hershamin.me

theme: jekyll-theme-chirpy

title: Sling Tsi Builder Blog
tagline: building and flying is life
description: Builder blog for building the Sling Tsi kit plane, a 4 seater cross-country cruiser

timezone: America/Chicago
